/* eslint-disable import/no-unresolved */
'use client';

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';

import {
  Box,
  Button,
  Card,
  CardContent,
  Chip,
  Divider,
  FormControl,
  FormControlLabel,
  Grid,
  IconButton,
  InputLabel,
  MenuItem,
  Select,
  Stack,
  Switch,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  TextField,
  Typography,
  alpha,
  useTheme,
  Dialog,
  DialogActions,
  DialogContent,
  DialogTitle
} from '@mui/material';
import { useLocale, useTranslations } from 'next-intl';
import { useAuth } from '@/contexts/AuthContext';
import { BrandService } from '@/services/brand.service';
import apiClient from '@/lib/apiClient';

type ReportSectionKey = 'seo' | 'reputation' | 'listings';
type TemplatePreset = 'executive' | 'technical' | 'reputation';
type Frequency = 'daily' | 'weekly' | 'monthly';
type ReportStatus = 'Sent' | 'Opened' | 'Failed';
type ExportStatus = 'Processing' | 'Ready' | 'Failed';

type WhiteLabelSettings = {
  logoDataUrl: string | null;
  primaryColor: string;
  accentColor: string;
  title: string;
  footer: string;
  intro: string;
};

type ScheduleConfig = {
  frequency: Frequency;
  recipients: string[];
  seoDropThreshold: number;
  enableTrigger: boolean;
  nextRunAt?: string | null;
};

type VaultItem = {
  id: string;
  name: string;
  date: string;
  type: 'PDF' | 'CSV' | 'Excel';
  status: ReportStatus;
  shareToken: string;
  webUrl?: string | null;
};

type ExportJob = {
  id: string;
  label: string;
  status: ExportStatus;
  createdAt: string;
  resultUrl?: string | null;
};

const defaultWhiteLabel: WhiteLabelSettings = {
  logoDataUrl: null,
  primaryColor: '#0F172A',
  accentColor: '#2563EB',
  title: 'Monthly Performance Report',
  footer: 'Confidential | Generated by ReviewRise',
  intro: 'A focused summary of performance highlights and next steps.'
};

const ReportsCenter = () => {
  const t = useTranslations('dashboard');
  const theme = useTheme();
  const { user } = useAuth();
  const locale = useLocale();

  const [sections, setSections] = useState<Record<ReportSectionKey, boolean>>({
    seo: true,
    reputation: true,
    listings: true
  });

  const [sectionOrder, setSectionOrder] = useState<ReportSectionKey[]>(['seo', 'reputation', 'listings']);
  const [preset, setPreset] = useState<TemplatePreset>('executive');
  const [whiteLabel, setWhiteLabel] = useState<WhiteLabelSettings>(defaultWhiteLabel);

  const [schedule, setSchedule] = useState<ScheduleConfig>({
    frequency: 'weekly',
    recipients: ['client@agency.com'],
    seoDropThreshold: 5,
    enableTrigger: false,
    nextRunAt: null
  });

  const [vaultItems, setVaultItems] = useState<VaultItem[]>([]);
  const [exportJobs, setExportJobs] = useState<ExportJob[]>([]);
  const [previewOpen, setPreviewOpen] = useState(false);

  const [businessId, setBusinessId] = useState<string | null>(null);
  const [businesses, setBusinesses] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [shareDialogOpen, setShareDialogOpen] = useState(false);
  const [sharePassword, setSharePassword] = useState('');
  const [sharePasswordConfirm, setSharePasswordConfirm] = useState('');
  const [shareTarget, setShareTarget] = useState<VaultItem | null>(null);
  const [shareLoading, setShareLoading] = useState(false);
  const [recipientError, setRecipientError] = useState<string | null>(null);
  const [initialized, setInitialized] = useState(false);
  const [scheduleDirty, setScheduleDirty] = useState(false);
  const [scheduleSaving, setScheduleSaving] = useState(false);

  const configSaveTimer = useRef<NodeJS.Timeout | null>(null);

  // const scheduleSaveTimer = useRef<NodeJS.Timeout | null>(null);

  useEffect(() => {
    const fetchBusinesses = async () => {
      if (!user?.id) return;
      setLoading(true);

      try {
        const responseData = await apiClient.get<any[]>(`/api/admin/users/${user.id}/businesses`)
          .then(res => res.data);

        if (responseData && responseData.length > 0) {
          setBusinesses(responseData);
          setBusinessId(responseData[0].id);
        } else {
          setErrorMessage(t('reportsCenter.emptyBusiness'));
        }
      } catch (error) {
        // eslint-disable-next-line no-console
        console.error('Failed to load businesses', error);
        setErrorMessage(t('reportsCenter.loadFailed'));
      } finally {
        setLoading(false);
      }
    };

    fetchBusinesses();
  }, [user?.id, t]);

  const fetchReportsCenterData = useCallback(async (targetBusinessId: string, includeConfig = true) => {
      setLoading(true);
      setErrorMessage(null);

      try {
        const requests: Promise<any>[] = [
          BrandService.listReportsCenterVault(targetBusinessId),
          BrandService.listReportsCenterExports(targetBusinessId)
        ];

        if (includeConfig) {
          requests.unshift(
            BrandService.getReportsCenterConfig(targetBusinessId),
            BrandService.getReportsCenterSchedule(targetBusinessId)
          );
        }

        const responses = await Promise.all(requests);
        const offset = includeConfig ? 2 : 0;

        const config = includeConfig ? responses[0] : null;
        const scheduleData = includeConfig ? responses[1] : null;
        const vault = responses[offset];
        const exports = responses[offset + 1];

        if (includeConfig && config && scheduleData) {
          setPreset((config.preset as TemplatePreset) || 'executive');
          setSections((config.sections as Record<ReportSectionKey, boolean>) || { seo: true, reputation: true, listings: true });
          setSectionOrder((config.sectionOrder as ReportSectionKey[]) || ['seo', 'reputation', 'listings']);
          setWhiteLabel((config.whiteLabel as WhiteLabelSettings) || defaultWhiteLabel);

          setSchedule({
            frequency: scheduleData.frequency,
            recipients: scheduleData.recipients || [],
            seoDropThreshold: scheduleData.seoDropThreshold || 5,
            enableTrigger: scheduleData.triggerEnabled,
            nextRunAt: scheduleData.nextRunAt
          });
          setScheduleDirty(false);
        }

        const vaultItems = Array.isArray(vault)
          ? vault
          : Array.isArray((vault as any)?.items)
            ? (vault as any).items
            : [];

        const exportItems = Array.isArray(exports)
          ? exports
          : Array.isArray((exports as any)?.items)
            ? (exports as any).items
            : [];

        setVaultItems(
          vaultItems.map((item: any) => ({
            id: item.id,
            name: item.name,
            date: formatDate(item.generatedAt) || formatDate(item.deliveredAt) || '',
            type: item.type,
            status: item.status || 'Sent',
            shareToken: item.shareToken || '',
            webUrl: item.webUrl || null
          }))
        );

        setExportJobs(
          exportItems.map((job: any) => ({
            id: job.id,
            label: job.type,
            status: job.status,
            createdAt: new Date(job.createdAt).toLocaleString(),
            resultUrl: job.resultUrl || null
          }))
        );

        if (includeConfig) {
          setInitialized(true);
        }
      } catch (error) {
        // eslint-disable-next-line no-console
        console.error('Failed to load reports center', error);
        setErrorMessage(t('reportsCenter.loadFailed'));
      } finally {
        setLoading(false);
      }
    }, [t]);

  useEffect(() => {
    if (!businessId) return;
    setInitialized(false);
    fetchReportsCenterData(businessId, true);
  }, [businessId, fetchReportsCenterData]);

  useEffect(() => {
    if (!initialized || !businessId) return;

    const interval = setInterval(() => {
      fetchReportsCenterData(businessId, false);
    }, 30000);

    return () => clearInterval(interval);
  }, [initialized, businessId, fetchReportsCenterData]);

  useEffect(() => {
    if (!initialized || !businessId) return;

    if (configSaveTimer.current) clearTimeout(configSaveTimer.current);

    configSaveTimer.current = setTimeout(() => {
      BrandService.updateReportsCenterConfig(businessId, {
        preset,
        sections,
        sectionOrder,
        whiteLabel
      }).catch(() => {
        setErrorMessage(t('reportsCenter.saveFailed'));
      });
    }, 600);
  }, [preset, sections, sectionOrder, whiteLabel, businessId, initialized, t]);

  const handleSaveSchedule = async () => {
    if (!businessId) return;
    setScheduleSaving(true);
    setErrorMessage(null);

    try {
      const updated = await BrandService.updateReportsCenterSchedule(businessId, {
        frequency: schedule.frequency,
        recipients: schedule.recipients,
        triggerEnabled: schedule.enableTrigger,
        seoDropThreshold: schedule.seoDropThreshold
      });

      if (updated?.nextRunAt) {
        setSchedule((prev) => ({ ...prev, nextRunAt: updated.nextRunAt }));
      }

      setScheduleDirty(false);
      } catch {
        setErrorMessage(t('reportsCenter.saveFailed'));
      } finally {
        setScheduleSaving(false);
      }
    };

  useEffect(() => {
    if (!businessId) return;
    if (!exportJobs.some(job => job.status === 'Processing')) return;

    const interval = setInterval(async () => {
      const exports = await BrandService.listReportsCenterExports(businessId);

      setExportJobs(
        (exports || []).map(job => ({
          id: job.id,
          label: job.type,
          status: job.status,
          createdAt: new Date(job.createdAt).toLocaleString(),
          resultUrl: job.resultUrl || null
        }))
      );
    }, 8000);

    return () => clearInterval(interval);
  }, [exportJobs, businessId]);

  const selectedSections = sectionOrder.filter((key) => sections[key]);

  const handlePreset = (next: TemplatePreset) => {
    setPreset(next);

    if (next === 'executive') {
      setSections({ seo: true, reputation: true, listings: true });
      setSectionOrder(['seo', 'reputation', 'listings']);
    }

    if (next === 'technical') {
      setSections({ seo: true, reputation: false, listings: true });
      setSectionOrder(['seo', 'listings', 'reputation']);
    }

    if (next === 'reputation') {
      setSections({ seo: false, reputation: true, listings: true });
      setSectionOrder(['reputation', 'listings', 'seo']);
    }
  };

  const handleToggleSection = (key: ReportSectionKey) => {
    setSections((prev) => ({ ...prev, [key]: !prev[key] }));
  };

  const handleLogoUpload = async (file: File | null) => {
    if (!file) return;

    if (file.size > 1_000_000) {
      setErrorMessage(t('reportsCenter.whiteLabel.logoTooLarge'));

      return;
    }

    try {
      const uploaded = await BrandService.uploadFile(file);

      if (uploaded?.url) {
        setWhiteLabel((prev) => ({ ...prev, logoDataUrl: uploaded.url }));
      }
    } catch {
      setErrorMessage(t('reportsCenter.whiteLabel.logoUploadFailed'));
    }
  };

  const handleAddRecipient = (value: string) => {
    const trimmed = value.trim();

    if (!trimmed) return;
    const isValid = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(trimmed);

    if (!isValid) {
      setRecipientError(t('reportsCenter.schedule.invalidEmail'));

      return;
    }

    setRecipientError(null);
    if (schedule.recipients.includes(trimmed)) return;
    setScheduleDirty(true);
    setSchedule((prev) => ({ ...prev, recipients: [...prev.recipients, trimmed] }));
  };

  const handleRemoveRecipient = (email: string) => {
    setScheduleDirty(true);
    setSchedule((prev) => ({ ...prev, recipients: prev.recipients.filter((item) => item !== email) }));
  };

  const nextRunLabel = useMemo(() => {
    if (schedule.nextRunAt) {
      return new Date(schedule.nextRunAt).toLocaleString();
    }

    const now = new Date();
    const next = new Date(now);

    if (schedule.frequency === 'daily') next.setDate(now.getDate() + 1);
    if (schedule.frequency === 'weekly') next.setDate(now.getDate() + 7);
    if (schedule.frequency === 'monthly') next.setMonth(now.getMonth() + 1);

    return next.toLocaleString();
  }, [schedule.frequency, schedule.nextRunAt]);

  const handleGenerateReport = async () => {
    if (!businessId) return;

    try {
      const run = await BrandService.generateReportsCenterRun(businessId);
      
      setVaultItems((prev) => [
        {
          id: run.id,
          name: run.name,
          date: formatDate(run.generatedAt) || formatDate(run.deliveredAt) || new Date().toLocaleString(),
          type: run.type,
          status: run.status || 'Sent',
          shareToken: run.shareToken || '',
          webUrl: run.webUrl || null
        },
        ...prev
      ]);
    } catch {
      setErrorMessage(t('reportsCenter.generateFailed'));
    }
  };

  const handleExport = async (label: string) => {
    if (!businessId) return;

    try {
      const job = await BrandService.createReportsCenterExport(businessId, { type: label });
      const normalizedUrl = job.resultUrl?.replace(/^\/api\/v1\/brands\//, '/api/brands/') ?? null;

      setExportJobs((prev) => [
        {
          id: job.id,
          label: job.type,
          status: job.status,
          createdAt: new Date(job.createdAt).toLocaleString(),
          resultUrl: normalizedUrl
        },
        ...prev
      ]);
    } catch {
      setErrorMessage(t('reportsCenter.exportFailed'));
    }
  };

  const handleCopyLink = (item: VaultItem) => {
    setShareTarget(item);
    setSharePassword('');
    setSharePasswordConfirm('');
    setShareDialogOpen(true);
  };

  const copyShareUrl = (target: VaultItem) => {
    const sharePath = target.webUrl || `/reports-center/share/${target.shareToken}`;
    const localizedPath = sharePath.startsWith('/') ? `/${locale}${sharePath}` : `/${locale}/${sharePath}`;

    navigator.clipboard.writeText(`${window.location.origin}${localizedPath}`);
  };

  const handleConfirmShare = async () => {
    if (!businessId || !shareTarget) return;
    
    if (sharePassword !== sharePasswordConfirm) {
      setErrorMessage(t('reportsCenter.share.passwordMismatch'));

      return;
    }

    setShareLoading(true);

    try {
      const run = await BrandService.generateReportsCenterRun(businessId, {
        password: sharePassword || null
      });

      setVaultItems((prev) => [
        {
          id: run.id,
          name: run.name,
          date: formatDate(run.generatedAt) || formatDate(run.deliveredAt) || new Date().toLocaleString(),
          type: run.type,
          status: run.status || 'Sent',
          shareToken: run.shareToken || '',
          webUrl: run.webUrl || null
        },
        ...prev
      ]);

      copyShareUrl({
        id: run.id,
        name: run.name,
        date: formatDate(run.generatedAt) || formatDate(run.deliveredAt) || new Date().toLocaleString(),
        type: run.type,
        status: run.status || 'Sent',
        shareToken: run.shareToken || '',
        webUrl: run.webUrl || null
      });

      setShareDialogOpen(false);
      setShareTarget(null);
    } catch {
      setErrorMessage(t('reportsCenter.share.generateFailed'));
    } finally {
      setShareLoading(false);
    }
  };

  const handleDownload = (item: VaultItem) => {
    if (!businessId) return;
    const base = (process.env.NEXT_PUBLIC_API_URL || '').replace(/\/+$/, '');
    const url = `${base}/api/brands/${businessId}/reports-center/runs/${item.id}/pdf`;

    window.open(url, '_blank');
  };

  const handleRerun = async (item: VaultItem) => {
    if (!businessId) return;

    try {
      const run = await BrandService.rerunReportsCenter(businessId, item.id);

      setVaultItems((prev) => [
        {
          id: run.id,
          name: run.name,
          date: new Date(run.generatedAt).toLocaleString(),
          type: run.type,
          status: run.status,
          shareToken: run.shareToken || '',
          webUrl: run.webUrl || null
        },
        ...prev
      ]);
    } catch {
      setErrorMessage(t('reportsCenter.generateFailed'));
    }
  };

  const handleDownloadExport = (job: ExportJob) => {
    if (!businessId) return;
    const base = (process.env.NEXT_PUBLIC_API_URL || '').replace(/\/+$/, '');
    const normalized = job.resultUrl?.replace(/^\/api\/v1\/brands\//, '/api/brands/') ?? null;
    const url = normalized || `/api/brands/${businessId}/reports-center/exports/${job.id}/download?format=csv`;

    window.open(`${base}${url}`, '_blank');
  };

  const formatDate = (value?: string | null) => {
    if (!value) return '';
    const parsed = new Date(value);

    if (Number.isNaN(parsed.getTime())) return '';

    return parsed.toLocaleString();
  };

  const previewContent = useMemo(() => ({
    title: whiteLabel.title,
    intro: whiteLabel.intro,
    footer: whiteLabel.footer
  }), [whiteLabel]);

  const PreviewPanel = useCallback(() => (
    <Box
      sx={{
        borderRadius: 3,
        border: `1px solid ${alpha(theme.palette.primary.main, 0.18)}`,
        overflow: 'hidden',
        backgroundColor: theme.palette.background.paper
      }}
    >
      <Box
        sx={{
          p: 3,
          background: `linear-gradient(120deg, ${whiteLabel.primaryColor}, ${whiteLabel.accentColor})`,
          color: '#fff'
        }}
      >
        <Stack direction="row" spacing={2} alignItems="center">
          {whiteLabel.logoDataUrl ? (
            <Box
              component="img"
              src={whiteLabel.logoDataUrl}
              alt={t('reportsCenter.preview.logoAlt')}
              sx={{ height: 40, borderRadius: 1, backgroundColor: '#fff', p: 0.5 }}
            />
          ) : (
            <Box
              sx={{
                height: 40,
                width: 40,
                borderRadius: 1,
                backgroundColor: alpha('#fff', 0.2),
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                fontWeight: 700
              }}
            >
              {t('reportsCenter.preview.logoFallback')}
            </Box>
          )}
          <Box>
            <Typography variant="h5" fontWeight={800}>
              {previewContent.title}
            </Typography>
            <Typography variant="body2" sx={{ opacity: 0.8 }}>
              {t('reportsCenter.preview.generatedOn', { date: new Date().toLocaleDateString() })}
            </Typography>
          </Box>
        </Stack>
      </Box>
      <Box sx={{ p: 3 }}>
        <Typography variant="subtitle1" fontWeight={700} gutterBottom>
          {t('reportsCenter.preview.introTitle')}
        </Typography>
        <Typography variant="body2" color="text.secondary" mb={2}>
          {previewContent.intro}
        </Typography>
        <Divider sx={{ mb: 2 }} />
        <Stack spacing={1.5}>
          {selectedSections.map((section) => (
            <Box key={section} sx={{ p: 2, borderRadius: 2, border: `1px solid ${theme.palette.divider}` }}>
              <Typography fontWeight={700}>{t(`reportsCenter.sections.${section}`)}</Typography>
              <Typography variant="body2" color="text.secondary">
                {t(`reportsCenter.sectionHints.${section}`)}
              </Typography>
            </Box>
          ))}
        </Stack>
      </Box>
      <Box sx={{ p: 2, backgroundColor: alpha(theme.palette.primary.main, 0.04) }}>
        <Typography variant="caption" color="text.secondary">
          {previewContent.footer}
        </Typography>
      </Box>
    </Box>
  ), [
    previewContent.footer,
    previewContent.intro,
    previewContent.title,
    selectedSections,
    t,
    theme.palette.background.paper,
    theme.palette.divider,
    theme.palette.primary.main,
    whiteLabel.accentColor,
    whiteLabel.logoDataUrl,
    whiteLabel.primaryColor
  ]);

  if (loading) {
    return (
      <Box sx={{ py: 4 }}>
        <Typography color="text.secondary">{t('reportsCenter.loading')}</Typography>
      </Box>
    );
  }

  return (
    <Box sx={{ py: 4 }}>
      <Stack spacing={4}>
        <Card sx={{ p: 4, borderRadius: 3 }}>
          <Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" alignItems={{ xs: 'flex-start', md: 'center' }} spacing={2}>
            <Box>
              <Typography variant="h4" fontWeight={800} gutterBottom>
                {t('reportsCenter.title')}
              </Typography>
              <Typography color="text.secondary">
                {t('reportsCenter.subtitle')}
              </Typography>
            </Box>
            <Stack direction={{ xs: 'column', sm: 'row' }} spacing={2} alignItems={{ xs: 'stretch', sm: 'center' }}>
              <FormControl size="small" sx={{ minWidth: 220 }}>
                <InputLabel>{t('reportsCenter.business')}</InputLabel>
                <Select
                  value={businessId || ''}
                  label={t('reportsCenter.business')}
                  onChange={(event) => setBusinessId(event.target.value)}
                >
                  {businesses.map((business) => (
                    <MenuItem key={business.id} value={business.id}>{business.name}</MenuItem>
                  ))}
                </Select>
              </FormControl>
              <Button variant="outlined" onClick={() => setPreviewOpen((prev) => !prev)}>
                {previewOpen ? t('reportsCenter.preview.close') : t('reportsCenter.preview.cta')}
              </Button>
              <Button variant="contained" onClick={handleGenerateReport}>
                {t('reportsCenter.generateReport')}
              </Button>
            </Stack>
          </Stack>
        </Card>

        {errorMessage ? (
          <Card sx={{ p: 3, borderRadius: 3, border: `1px solid ${alpha(theme.palette.error.main, 0.2)}` }}>
            <Typography color="error.main">{errorMessage}</Typography>
          </Card>
        ) : null}

        <Grid container spacing={4}>
          <Grid size={{ xs: 12, md: 6 }}>
            <Card sx={{ borderRadius: 3 }}>
              <CardContent>
                <Typography variant="h6" fontWeight={700} gutterBottom>
                  {t('reportsCenter.builder.title')}
                </Typography>
                <Typography variant="body2" color="text.secondary" mb={3}>
                  {t('reportsCenter.builder.subtitle')}
                </Typography>
                <FormControl size="small" fullWidth sx={{ mb: 3 }}>
                  <InputLabel>{t('reportsCenter.templates.title')}</InputLabel>
                  <Select
                    value={preset}
                    label={t('reportsCenter.templates.title')}
                    onChange={(event) => handlePreset(event.target.value as TemplatePreset)}
                  >
                    <MenuItem value="executive">{t('reportsCenter.templates.executive')}</MenuItem>
                    <MenuItem value="technical">{t('reportsCenter.templates.technical')}</MenuItem>
                    <MenuItem value="reputation">{t('reportsCenter.templates.reputation')}</MenuItem>
                  </Select>
                </FormControl>
                <Stack spacing={2}>
                  {sectionOrder.map((section) => (
                    <Box key={section} sx={{ p: 2, borderRadius: 2, border: `1px solid ${theme.palette.divider}` }}>
                      <Stack direction="row" spacing={2} alignItems="center">
                        <Switch checked={sections[section]} onChange={() => handleToggleSection(section)} />
                        <Box>
                          <Typography fontWeight={700}>{t(`reportsCenter.sections.${section}`)}</Typography>
                          <Typography variant="body2" color="text.secondary">
                            {t(`reportsCenter.sectionHints.${section}`)}
                          </Typography>
                        </Box>
                      </Stack>
                    </Box>
                  ))}
                </Stack>

              </CardContent>
            </Card>
          </Grid>

          <Grid size={{ xs: 12, md: 6 }}>
            <Card sx={{ borderRadius: 3 }}>
              <CardContent>
                <Typography variant="h6" fontWeight={700} gutterBottom>
                  {t('reportsCenter.schedule.title')}
                </Typography>
                <Typography variant="body2" color="text.secondary" mb={2}>
                  {t('reportsCenter.schedule.subtitle')}
                </Typography>
                <Stack spacing={2}>
                  <FormControl fullWidth>
                    <InputLabel>{t('reportsCenter.schedule.frequency')}</InputLabel>
                    <Select
                      label={t('reportsCenter.schedule.frequency')}
                      value={schedule.frequency}
                      onChange={(event) => {
                        setScheduleDirty(true);
                        setSchedule((prev) => ({ ...prev, frequency: event.target.value as Frequency }));
                      }}
                    >
                      <MenuItem value="daily">{t('reportsCenter.schedule.daily')}</MenuItem>
                      <MenuItem value="weekly">{t('reportsCenter.schedule.weekly')}</MenuItem>
                      <MenuItem value="monthly">{t('reportsCenter.schedule.monthly')}</MenuItem>
                    </Select>
                  </FormControl>
                  <TextField
                    label={t('reportsCenter.schedule.recipients')}
                    placeholder={t('reportsCenter.schedule.recipientsHint')}
                    error={Boolean(recipientError)}
                    helperText={recipientError || ' '}
                    onKeyDown={(event) => {
                      if (event.key === 'Enter') {
                        event.preventDefault();
                        handleAddRecipient((event.target as HTMLInputElement).value);
                        (event.target as HTMLInputElement).value = '';
                      }
                    }}
                  />
                  <Stack direction="row" spacing={1} flexWrap="wrap">
                    {schedule.recipients.map((email) => (
                      <Chip key={email} label={email} onDelete={() => handleRemoveRecipient(email)} />
                    ))}
                  </Stack>
                  <FormControlLabel
                    control={
                      <Switch
                        checked={schedule.enableTrigger}
                        onChange={(event) => {
                          setScheduleDirty(true);
                          setSchedule((prev) => ({ ...prev, enableTrigger: event.target.checked }));
                        }}
                      />
                    }
                    label={t('reportsCenter.schedule.enableTrigger')}
                  />
                  {schedule.enableTrigger && (
                    <TextField
                      label={t('reportsCenter.schedule.triggerLabel')}
                      type="number"
                      value={schedule.seoDropThreshold}
                      onChange={(event) => {
                        setScheduleDirty(true);
                        setSchedule((prev) => ({ ...prev, seoDropThreshold: Number(event.target.value) }));
                      }}
                    />
                  )}
                  <Box sx={{ p: 2, borderRadius: 2, border: `1px dashed ${theme.palette.divider}` }}>
                    <Stack direction={{ xs: 'column', sm: 'row' }} spacing={2} justifyContent="space-between" alignItems={{ xs: 'flex-start', sm: 'center' }}>
                      <Typography variant="body2" color="text.secondary">
                        {t('reportsCenter.schedule.nextRun', { date: nextRunLabel })}
                      </Typography>
                      <Button variant="contained" size="small" onClick={handleSaveSchedule} disabled={!scheduleDirty || scheduleSaving}>
                        {scheduleSaving ? t('reportsCenter.schedule.saving') : t('reportsCenter.schedule.save')}
                      </Button>
                    </Stack>
                  </Box>
                </Stack>
              </CardContent>
            </Card>
          </Grid>
        </Grid>

        <Card sx={{ borderRadius: 3 }}>
          <CardContent>
            <Typography variant="h6" fontWeight={700} gutterBottom>
              {t('reportsCenter.whiteLabel.title')}
            </Typography>
            <Typography variant="body2" color="text.secondary" mb={2}>
              {t('reportsCenter.whiteLabel.subtitle')}
            </Typography>
            <Stack spacing={2}>
              <Button component="label" variant="outlined">
                {t('reportsCenter.whiteLabel.uploadLogo')}
                <input hidden type="file" accept="image/*" onChange={(event) => handleLogoUpload(event.target.files?.[0] || null)} />
              </Button>
              {whiteLabel.logoDataUrl ? (
                <Box
                  sx={{
                    borderRadius: 2,
                    border: `1px dashed ${theme.palette.divider}`,
                    p: 2,
                    display: 'flex',
                    alignItems: 'center',
                    gap: 2,
                    position: 'relative'
                  }}
                >
                  <IconButton
                    size="small"
                    onClick={() => setWhiteLabel((prev) => ({ ...prev, logoDataUrl: null }))}
                    sx={{ position: 'absolute', top: 8, right: 8 }}
                  >
                    <i className="tabler-x" />
                  </IconButton>
                  <Box
                    component="img"
                    src={whiteLabel.logoDataUrl}
                    alt={t('reportsCenter.preview.logoAlt')}
                    sx={{ width: 72, height: 72, objectFit: 'contain' }}
                  />
                  <Typography variant="body2" color="text.secondary">
                    {t('reportsCenter.whiteLabel.logoPreview')}
                  </Typography>
                </Box>
              ) : null}
              <Grid container spacing={2}>
                <Grid size={{ xs: 6 }}>
                  <TextField
                    label={t('reportsCenter.whiteLabel.primaryColor')}
                    type="color"
                    fullWidth
                    value={whiteLabel.primaryColor}
                    onChange={(event) => setWhiteLabel((prev) => ({ ...prev, primaryColor: event.target.value }))}
                  />
                </Grid>
                <Grid size={{ xs: 6 }}>
                  <TextField
                    label={t('reportsCenter.whiteLabel.accentColor')}
                    type="color"
                    fullWidth
                    value={whiteLabel.accentColor}
                    onChange={(event) => setWhiteLabel((prev) => ({ ...prev, accentColor: event.target.value }))}
                  />
                </Grid>
              </Grid>
              <TextField
                label={t('reportsCenter.whiteLabel.reportTitle')}
                value={whiteLabel.title}
                onChange={(event) => setWhiteLabel((prev) => ({ ...prev, title: event.target.value }))}
              />
              <TextField
                label={t('reportsCenter.whiteLabel.intro')}
                value={whiteLabel.intro}
                onChange={(event) => setWhiteLabel((prev) => ({ ...prev, intro: event.target.value }))}
                multiline
                minRows={2}
              />
              <TextField
                label={t('reportsCenter.whiteLabel.footer')}
                value={whiteLabel.footer}
                onChange={(event) => setWhiteLabel((prev) => ({ ...prev, footer: event.target.value }))}
              />
            </Stack>
          </CardContent>
        </Card>

        <Grid container spacing={4}>
          <Grid size={{ xs: 12 }}>
            <Card sx={{ borderRadius: 3 }}>
              <CardContent>
                <Typography variant="h6" fontWeight={700} gutterBottom>
                  {t('reportsCenter.vault.title')}
                </Typography>
                {vaultItems.length === 0 ? (
                  <Typography color="text.secondary">{t('reportsCenter.vault.empty')}</Typography>
                ) : (
                  <TableContainer sx={{ borderRadius: 2, border: `1px solid ${theme.palette.divider}` }}>
                    <Table size="small">
                      <TableHead sx={{ backgroundColor: alpha(theme.palette.primary.main, 0.04) }}>
                        <TableRow>
                          <TableCell sx={{ fontWeight: 700 }}>{t('reportsCenter.vault.columns.name')}</TableCell>
                          <TableCell sx={{ fontWeight: 700 }}>{t('reportsCenter.vault.columns.date')}</TableCell>
                          <TableCell sx={{ fontWeight: 700 }}>{t('reportsCenter.vault.columns.type')}</TableCell>
                          <TableCell sx={{ fontWeight: 700 }}>{t('reportsCenter.vault.columns.status')}</TableCell>
                          <TableCell align="right" sx={{ fontWeight: 700 }}>{t('reportsCenter.vault.columns.actions')}</TableCell>
                        </TableRow>
                      </TableHead>
                      <TableBody>
                        {vaultItems.map((item, index) => (
                          <TableRow key={item.id || `${item.name}-${item.date}-${index}`} hover>
                            <TableCell>
                              <Typography fontWeight={600}>{item.name}</Typography>
                            </TableCell>
                            <TableCell>
                              <Typography variant="body2" color="text.secondary">{item.date}</Typography>
                            </TableCell>
                            <TableCell>
                              <Chip label={item.type} variant="outlined" size="small" />
                            </TableCell>
                            <TableCell>
                              <Chip label={item.status} size="small" color={item.status === 'Failed' ? 'error' : item.status === 'Opened' ? 'info' : 'success'} />
                            </TableCell>
                            <TableCell align="right">
                              <Stack direction="row" spacing={1} justifyContent="flex-end">
                                <Button variant="outlined" size="small" onClick={() => handleDownload(item)}>
                                  {t('reportsCenter.vault.download')}
                                </Button>
                                <Button variant="outlined" size="small" onClick={() => handleCopyLink(item)}>
                                  {t('reportsCenter.vault.copyLink')}
                                </Button>
                                <Button variant="text" size="small" onClick={() => handleRerun(item)}>
                                  {t('reportsCenter.vault.rerun')}
                                </Button>
                              </Stack>
                            </TableCell>
                          </TableRow>
                        ))}
                      </TableBody>
                    </Table>
                  </TableContainer>
                )}
              </CardContent>
            </Card>
          </Grid>
        </Grid>

        <Card sx={{ borderRadius: 3 }}>
          <CardContent>
            <Typography variant="h6" fontWeight={700} gutterBottom>
              {t('reportsCenter.exports.title')}
            </Typography>
            <Typography variant="body2" color="text.secondary" mb={2}>
              {t('reportsCenter.exports.subtitle')}
            </Typography>
            <Stack direction={{ xs: 'column', md: 'row' }} spacing={2}>
              <Button variant="outlined" onClick={() => handleExport(t('reportsCenter.exports.keywordHistory'))}>
                {t('reportsCenter.exports.keywordHistory')}
              </Button>
              <Button variant="outlined" onClick={() => handleExport(t('reportsCenter.exports.reviewList'))}>
                {t('reportsCenter.exports.reviewList')}
              </Button>
              <Button variant="outlined" onClick={() => handleExport(t('reportsCenter.exports.syncLogs'))}>
                {t('reportsCenter.exports.syncLogs')}
              </Button>
            </Stack>
            <Stack spacing={1} mt={3}>
              {exportJobs.map((job) => (
                <Box key={job.id} sx={{ p: 2, borderRadius: 2, border: `1px dashed ${theme.palette.divider}` }}>
                  <Stack direction="row" justifyContent="space-between" alignItems="center" spacing={2}>
                    <Typography fontWeight={600}>{job.label}</Typography>
                    <Stack direction="row" spacing={1} alignItems="center">
                      <Chip label={job.status} color={job.status === 'Ready' ? 'success' : job.status === 'Failed' ? 'error' : 'warning'} />
                      {job.status === 'Ready' ? (
                        <Button size="small" variant="outlined" onClick={() => handleDownloadExport(job)}>
                          {t('reportsCenter.exports.download')}
                        </Button>
                      ) : null}
                    </Stack>
                  </Stack>
                  <Typography variant="caption" color="text.secondary">
                    {job.createdAt}
                  </Typography>
                </Box>
              ))}
            </Stack>
          </CardContent>
        </Card>

        <Dialog open={shareDialogOpen} onClose={() => setShareDialogOpen(false)} maxWidth="xs" fullWidth>
          <DialogTitle>{t('reportsCenter.share.dialogTitle')}</DialogTitle>
          <DialogContent>
            <Stack spacing={2} sx={{ mt: 1 }}>
              <Typography variant="body2" color="text.secondary">
                {t('reportsCenter.share.dialogSubtitle')}
              </Typography>
              <TextField
                label={t('reportsCenter.share.password')}
                type="password"
                value={sharePassword}
                onChange={(event) => setSharePassword(event.target.value)}
                autoComplete="new-password"
              />
              <TextField
                label={t('reportsCenter.share.passwordConfirm')}
                type="password"
                value={sharePasswordConfirm}
                onChange={(event) => setSharePasswordConfirm(event.target.value)}
                autoComplete="new-password"
              />
            </Stack>
          </DialogContent>
          <DialogActions sx={{ px: 3, pb: 2 }}>
            <Button variant="text" onClick={() => setShareDialogOpen(false)}>
              {t('reportsCenter.share.cancel')}
            </Button>
            <Button variant="contained" onClick={handleConfirmShare} disabled={shareLoading}>
              {shareLoading ? t('reportsCenter.share.generating') : t('reportsCenter.share.generateLink')}
            </Button>
          </DialogActions>
        </Dialog>

        {previewOpen && (
          <Box>
            <PreviewPanel />
          </Box>
        )}
      </Stack>
    </Box>
  );
};

export default ReportsCenter;
