import { prisma } from '@platform/db';
import { buildReportsCenterPdf } from './reports-center-pdf';
import * as ReviewService from './review.service';
import crypto from 'crypto';

type Frequency = 'daily' | 'weekly' | 'monthly';
type ExportPayload = { body: string | Buffer; filename: string; contentType: string };

const DEFAULT_CONFIG = {
  preset: 'executive',
  sections: {
    seo: true,
    reputation: true,
    listings: true
  },
  sectionOrder: ['seo', 'reputation', 'listings'],
  whiteLabel: {
    logoDataUrl: null,
    primaryColor: '#0F172A',
    accentColor: '#2563EB',
    title: 'Monthly Performance Report',
    footer: 'Confidential | Generated by ReviewRise',
    intro: 'A focused summary of performance highlights and next steps.'
  }
};

const hashPassword = (value: string) =>
  crypto.createHash('sha256').update(value).digest('hex');

const addFrequency = (date: Date, frequency: Frequency) => {
  const next = new Date(date);
  if (frequency === 'daily') next.setDate(next.getDate() + 1);
  if (frequency === 'weekly') next.setDate(next.getDate() + 7);
  if (frequency === 'monthly') next.setMonth(next.getMonth() + 1);
  return next;
};

export const getConfig = async (businessId: string) => {
  const existing = await prisma.reportsCenterConfig.findUnique({
    where: { businessId }
  });

  if (existing) return existing;

  return prisma.reportsCenterConfig.create({
    data: {
      businessId,
      preset: DEFAULT_CONFIG.preset,
      sections: DEFAULT_CONFIG.sections,
      sectionOrder: DEFAULT_CONFIG.sectionOrder,
      whiteLabel: DEFAULT_CONFIG.whiteLabel
    }
  });
};

export const updateConfig = async (businessId: string, payload: any) => {
  const config = await getConfig(businessId);
  return prisma.reportsCenterConfig.update({
    where: { id: config.id },
    data: {
      preset: payload.preset ?? config.preset,
      sections: payload.sections ?? config.sections,
      sectionOrder: payload.sectionOrder ?? config.sectionOrder,
      whiteLabel: payload.whiteLabel ?? config.whiteLabel
    }
  });
};

export const getSchedule = async (businessId: string) => {
  const config = await getConfig(businessId);
  const schedule = await prisma.reportsCenterSchedule.findUnique({
    where: { configId: config.id }
  });

  if (schedule) return schedule;

  return prisma.reportsCenterSchedule.create({
    data: {
      businessId,
      configId: config.id,
      frequency: 'weekly',
      recipients: ['client@agency.com'],
      nextRunAt: addFrequency(new Date(), 'weekly')
    }
  });
};

export const updateSchedule = async (businessId: string, payload: any) => {
  const config = await getConfig(businessId);
  const existing = await prisma.reportsCenterSchedule.findUnique({
    where: { configId: config.id }
  });

  if (existing) {
    return prisma.reportsCenterSchedule.update({
      where: { id: existing.id },
      data: {
        frequency: payload.frequency ?? existing.frequency,
        recipients: payload.recipients ?? existing.recipients,
        triggerEnabled: payload.triggerEnabled ?? existing.triggerEnabled,
        seoDropThreshold: payload.seoDropThreshold ?? existing.seoDropThreshold,
        nextRunAt: payload.nextRunAt ?? existing.nextRunAt
      }
    });
  }

  return prisma.reportsCenterSchedule.create({
    data: {
      businessId,
      configId: config.id,
      frequency: payload.frequency ?? 'weekly',
      recipients: payload.recipients ?? ['client@agency.com'],
      triggerEnabled: payload.triggerEnabled ?? false,
      seoDropThreshold: payload.seoDropThreshold ?? 5,
      nextRunAt: payload.nextRunAt ?? addFrequency(new Date(), payload.frequency ?? 'weekly')
    }
  });
};

export const generateReportRun = async (businessId: string, options?: { password?: string | null }) => {
  const config = await getConfig(businessId);
  const whiteLabel = config.whiteLabel as any;
  const shareToken = crypto.randomBytes(8).toString('hex');
  const passwordHash = options?.password ? hashPassword(options.password) : null;
  const name = whiteLabel?.title || 'Business Report';
  const now = new Date();

  const run = await prisma.reportsCenterRun.create({
    data: {
      businessId,
      configId: config.id,
      name,
      type: 'PDF',
      status: 'Sent',
      generatedAt: now,
      deliveredAt: now,
      shareToken,
      sharePasswordHash: passwordHash,
      webUrl: `/reports-center/share/${shareToken}`,
      meta: {
        sections: config.sections,
        sectionOrder: config.sectionOrder,
        whiteLabel
      }
    }
  });

  return run;
};

export const listVault = async (businessId: string) => {
  return prisma.reportsCenterRun.findMany({
    where: { businessId },
    orderBy: { generatedAt: 'desc' }
  });
};

export const rerunReport = async (businessId: string, runId: string) => {
  const run = await prisma.reportsCenterRun.findFirst({
    where: { id: runId, businessId }
  });
  if (!run) return null;
  return generateReportRun(businessId);
};

export const createExportJob = async (businessId: string, type: string) => {
  return prisma.reportsCenterExportJob.create({
    data: {
      businessId,
      type,
      status: 'Processing'
    }
  });
};

export const listExportJobs = async (businessId: string) => {
  return prisma.reportsCenterExportJob.findMany({
    where: { businessId },
    orderBy: { createdAt: 'desc' }
  });
};

export const getShareReport = async (token: string) => {
  return prisma.reportsCenterRun.findFirst({
    where: { shareToken: token }
  });
};

export const validateSharePassword = (storedHash: string | null, password?: string | null) => {
  if (!storedHash) return true;
  if (!password) return false;
  return storedHash === hashPassword(password);
};

export const computeNextRun = addFrequency;

export const markOpened = async (runId: string) => {
  return prisma.reportsCenterRun.update({
    where: { id: runId },
    data: { openedAt: new Date(), status: 'Opened' }
  });
};

const formatSectionTitle = (key: string) => {
  if (key === 'seo') return 'SEO Performance';
  if (key === 'reputation') return 'Reputation & Reviews';
  if (key === 'listings') return 'Listings Consistency';
  return key;
};

const formatDateShort = (value?: Date | null) => {
  if (!value) return 'N/A';
  return value.toLocaleDateString();
};

const buildSectionContent = async (businessId: string) => {
  const latestVisibility = await prisma.visibilitySnapshot.findFirst({
    where: { businessId },
    orderBy: { capturedAt: 'desc' }
  });

  const reviewStats = await ReviewService.getReviewStats(businessId).catch(() => ({
    totalReviews: 0,
    averageRating: 0
  }));

  const breakdown = (latestVisibility?.breakdown || {}) as Record<string, any>;
  const listingsScore =
    breakdown.consistencyScore ?? breakdown.listingsScore ?? breakdown.citationsScore ?? null;

  return {
    seo: {
      bullets: [
        `Visibility score: ${latestVisibility?.score ?? 0}/100`,
        `Latest snapshot: ${formatDateShort(latestVisibility?.capturedAt)}`
      ]
    },
    reputation: {
      bullets: [
        `Average rating: ${reviewStats.averageRating || 0} / 5`,
        `Total reviews: ${reviewStats.totalReviews || 0}`
      ]
    },
    listings: {
      bullets: listingsScore !== null
        ? [
            `Listings consistency score: ${Number(listingsScore).toFixed(0)} / 100`,
            `Latest snapshot: ${formatDateShort(latestVisibility?.capturedAt)}`
          ]
        : [
            'Listings consistency data is not available yet.',
            'Connect directory sources to start tracking accuracy.'
          ]
    }
  };
};

const normalizeSections = (
  sectionsInput: unknown,
  sectionOrder: string[]
) => {
  if (Array.isArray(sectionsInput)) {
    return sectionsInput.length ? sectionsInput : sectionOrder;
  }

  if (sectionsInput && typeof sectionsInput === 'object') {
    const flags = sectionsInput as Record<string, boolean>;
    return sectionOrder.filter((section) => flags[section] !== false);
  }

  return sectionOrder;
};

export const generateReportHtml = async (runId: string, businessId: string) => {
  const run = await prisma.reportsCenterRun.findFirst({ where: { id: runId, businessId } });
  if (!run) throw new Error('Report not found');

  const config = await getConfig(businessId);
  const whiteLabel = (config.whiteLabel || {}) as any;
  const sectionOrder = (config.sectionOrder || ['seo', 'reputation', 'listings']) as string[];
  const sections = normalizeSections((run as any)?.sections || (config as any)?.sections, sectionOrder);
  const logoMarkup = whiteLabel.logoDataUrl
    ? `<img src="${whiteLabel.logoDataUrl}" alt="logo" style="height:32px;width:96px;object-fit:contain;" />`
    : `<div style="height:32px;width:96px;border-radius:8px;background:${whiteLabel.accentColor || '#2563EB'};color:#fff;display:flex;align-items:center;justify-content:center;font-weight:700;">RR</div>`;

  const sectionContent = await buildSectionContent(businessId);

  return `
    <html>
      <head>
        <style>
          :root { --primary: ${whiteLabel.primaryColor || '#0F172A'}; --accent: ${whiteLabel.accentColor || '#2563EB'}; }
          * { box-sizing: border-box; }
          body { font-family: 'Helvetica', Arial, sans-serif; margin: 0; color: #0f172a; background: #f1f5f9; min-height: 100vh; }
          .shell { max-width: 1100px; margin: 0 auto; padding: 28px 20px 40px; }
          .hero { background: linear-gradient(120deg, var(--primary), #111827); color: #fff; border-radius: 20px; padding: 28px; display: grid; gap: 16px; }
          .hero-top { display: flex; align-items: center; gap: 16px; }
          .hero h1 { margin: 0; font-size: 24px; letter-spacing: 0.2px; }
          .hero p { margin: 0; font-size: 12px; line-height: 1.6; opacity: 0.9; }
          .meta-row { display: flex; flex-wrap: wrap; gap: 10px; }
          .pill { background: rgba(255,255,255,0.15); border: 1px solid rgba(255,255,255,0.2); padding: 6px 12px; border-radius: 999px; font-size: 11px; }
          .content { margin-top: 20px; display: grid; gap: 14px; }
          .section { padding: 18px; border-radius: 16px; background: #ffffff; border: 1px solid #e2e8f0; box-shadow: 0 10px 24px rgba(15, 23, 42, 0.06); }
          .section h2 { margin: 0 0 8px; font-size: 14px; color: var(--accent); letter-spacing: 0.2px; }
          .section p { margin: 0; font-size: 12px; line-height: 1.6; color: #1f2937; }
          .section ul { margin: 0; padding-left: 18px; font-size: 12px; line-height: 1.6; color: #1f2937; }
          .section li { margin-bottom: 6px; }
          .footer { margin-top: 20px; padding: 14px 16px; background: #ffffff; border-radius: 14px; font-size: 10px; color: #64748b; text-align: center; border: 1px solid #e2e8f0; }
        </style>
      </head>
      <body>
        <div class="shell">
          <div class="hero">
            <div class="hero-top">
              ${logoMarkup}
              <div>
                <h1>${whiteLabel.title || 'Monthly Performance Report'}</h1>
                ${whiteLabel.intro ? `<p>${whiteLabel.intro}</p>` : ''}
              </div>
            </div>
            <div class="meta-row">
              <span class="pill">Report Type: Performance</span>
              <span class="pill">Generated: ${new Date().toLocaleDateString()}</span>
              <span class="pill">Status: Shareable</span>
            </div>
          </div>
          <div class="content">
            ${sections.map(section => {
              const bullets = sectionContent[section as keyof typeof sectionContent]?.bullets || [
                `Key findings and highlights for ${formatSectionTitle(section)} will appear here.`
              ];

              return `
                <div class="section">
                  <h2>${formatSectionTitle(section)}</h2>
                  <ul>${bullets.map(item => `<li>${item}</li>`).join('')}</ul>
                </div>
              `;
            }).join('')}
          </div>
          <div class="footer">${whiteLabel.footer || 'Confidential | Generated by ReviewRise'}</div>
        </div>
      </body>
    </html>
  `;
};

export const generateReportPdf = async (runId: string, businessId: string): Promise<Buffer> => {
  const run = await prisma.reportsCenterRun.findFirst({ where: { id: runId, businessId } });
  if (!run) {
    throw new Error('Report not found');
  }

  const config = await prisma.reportsCenterConfig.findFirst({ where: { businessId } });
  const sectionOrder = (config?.sectionOrder || ['seo', 'reputation', 'listings']) as string[];
  const sections = normalizeSections((run as any)?.sections || (config as any)?.sections, sectionOrder);
  const whiteLabel = (config?.whiteLabel || {}) as any;
  const sectionContent = await buildSectionContent(businessId);
  return buildReportsCenterPdf({
    sections,
    whiteLabel: whiteLabel as any,
    formatSectionTitle,
    sectionContent
  });
};

const buildExportRows = () => [
  ['Date', 'Metric', 'Value'],
  ['2024-02-01', 'Visibility', '78'],
  ['2024-02-02', 'Visibility', '81']
];

export const generateExportPayload = async (businessId: string, jobId: string, format: string): Promise<ExportPayload | null> => {
  const job = await prisma.reportsCenterExportJob.findFirst({ where: { id: jobId, businessId } });
  if (!job) return null;

  const rows = buildExportRows();
  const safeType = job.type.replace(/\s+/g, '-').toLowerCase();

  if (format === 'excel') {
    const body = rows.map(row => row.join('\\t')).join('\\n');
    return { body, filename: `${safeType}.xls`, contentType: 'application/vnd.ms-excel' };
  }

  const body = rows.map(row => row.map(cell => `"${cell}"`).join(',')).join('\n');
  return { body, filename: `${safeType}.csv`, contentType: 'text/csv' };
};
